GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiSmltIiwiaWF0IjoxNjQ4MTE5MTAyfQ.-hpmEVmsIGOYepN45b4KICcwqWYKgq92KqvPz2aez-Y




###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Jim"
}
